/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'title-lg': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
      },
      colors: {
        'on-primary': '#ffffff',
        'primary-container': '#3f51b5',
        'surface': '#fbf8ff',
        'on-primary-fixed': '#00105c',
        'surface-container-highest': '#e3e1ea',
        'inverse-primary': '#bac3ff',
        'on-tertiary': '#ffffff',
        'surface-bright': '#fbf8ff',
        'primary-fixed-dim': '#bac3ff',
        'surface-dim': '#dbd9e2',
        'inverse-on-surface': '#f2eff9',
        'surface-tint': '#4355b9',
        'on-primary-container': '#cacfff',
        'error-container': '#ffdad6',
        'background': '#fbf8ff',
        'error': '#ba1a1a',
        'on-background': '#1a1b22',
        'on-secondary': '#ffffff',
        'surface-container-low': '#f4f2fc',
        'surface-variant': '#e3e1ea',
        'on-error-container': '#93000a',
        'inverse-surface': '#2f3037',
        'tertiary-container': '#8f4700',
        'on-primary-fixed-variant': '#293ca0',
        'on-secondary-fixed': '#00201c',
        'tertiary-fixed': '#ffdcc6',
        'primary-fixed': '#dee0ff',
        'on-error': '#ffffff',
        'secondary-container': '#85f6e5',
        'on-surface': '#1a1b22',
        'on-surface-variant': '#454652',
        'primary': '#24389c',
        'on-tertiary-container': '#ffc7a2',
        'outline': '#757684',
        'secondary-fixed': '#85f6e5',
        'secondary-fixed-dim': '#67d9c9',
        'secondary': '#006a60',
        'on-secondary-fixed-variant': '#005048',
        'tertiary-fixed-dim': '#ffb784',
        'on-secondary-container': '#007166',
        'outline-variant': '#c5c5d4',
        'surface-container-lowest': '#ffffff',
        'surface-container': '#efedf6',
        'tertiary': '#6c3400',
        'surface-container-high': '#e9e7f0',
        'brand': {
          'dark': '#0a0a0f',
          'card': '#111118',
          'input': '#1a1a24',
          'accent': '#63dcb4',
        },
      },
      spacing: {
        'base': '8px',
        'xs': '4px',
        'sm': '12px',
        'md': '24px',
        'lg': '48px',
        'xl': '80px',
        'gutter': '24px',
        'margin-desktop': '64px',
        'margin-mobile': '16px',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
      keyframes: {
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'pulse-glow': {
          '0%, 100%': { opacity: '1', boxShadow: '0 0 20px rgba(99, 220, 180, 0.5)' },
          '50%': { opacity: '0.8', boxShadow: '0 0 40px rgba(99, 220, 180, 0.8)' },
        },
      },
      animation: {
        fadeUp: 'fadeUp 0.5s ease-out',
        'pulse-glow': 'pulse-glow 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
    },
  },
  plugins: [],
}